blog/urls.py
from django.urls import path

from . import views
from .views import (
    ArticleTemplateView, 
    HomePageTemplateView, 
    UserArticlesTemplateView, 
    ArticleDetailsTemplateView,
    UserArticleLikesTemplateView,
    EditUserTemplateView,
    RegisterUserTemplateView,
    ChangePassUserTemplateView)
from .api import NewArticleViewSet, UserViewSet, CommentViewSet, LikeViewSet

app_name = 'blog'
urlpatterns = [
    path('', views.home_page, name = "homepage"),
    path('article/<int:user_id>', views.user_articles, name = "userarticle"),
    path('article/liked', views.view_liked, name = "viewliked"),
    path('article/add', views.add_article, name = "addarticle"),
    path('article/add/comment/<int:article_id>', views.comment_add, name = "addcomment"),
    path('article/edit/comment/<int:comment_id>', views.comment_edit, name = "editcomment"),
    path('article/delete/comment/<int:comment_id>', views.comment_delete, name = "deletecomment"),
    path('article/delete/<int:article_id>', views.delete_article, name = "deletearticle"),
    path('article/details/<int:article_id>', views.article_details, name = "articledetails"),
    path('article/edit/<int:article_id>', views.edit_article, name = "editarticle"),
    path('article/like/<int:article_id>', views.article_like, name = "likearticle"),

    path('accounts/follow/<int:user_id>', views.user_follow, name = "followuser"),

    path('drf/homepage', HomePageTemplateView.as_view(), name = "drfhome"),
    path('drf/user/register', RegisterUserTemplateView.as_view(), name = "drfuserregister"),
    path('drf/user/edit', EditUserTemplateView.as_view(), name = "drfuseredit"),
    path('drf/user/change/password', ChangePassUserTemplateView.as_view(), name = "drfchangepass"),
    path('drf/user/article/<int:user_id>', UserArticlesTemplateView.as_view(), name = "drfuserarticle"),
    path('drf/article/details/<int:article_id>', ArticleDetailsTemplateView.as_view(), name = "drfarticledetails"),
    path('drf/user/article/likes', UserArticleLikesTemplateView.as_view(), name = "drfuserlikearticle"),
]

socialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blog.urls')),
    path('api/', include('blog.endpoints')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('accounts/login', views.LoginView.as_view(), name = "login"),
    path('accounts/logout', views.LogoutView.as_view(), name = "logout"),
    path('accounts/register', views.RegisterUserView.as_view(), name = "register"),
    path('accounts/forget/password', views.reset_password, name = "resetpass"),
    path('accounts/edit/user', views.EditUserView.as_view(), name = "edituser"),
    path('accounts/edit/password', views.EditPassword.as_view(), name = "editpass"),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.db.models import Count

from taggit.managers import TaggableManager

# Create your models here.

class Article(models.Model):
    title =  models.CharField(max_length = 200)
    description = models.TextField(null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_published = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)
    article_image = models.ImageField(upload_to='articleImage/', null=True, blank=True)
    is_featured = models.BooleanField(default=False)

    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

class FeaturedArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.article.title

class ArticleComments(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_published = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.article.title +" : " + self.content

    def number_of_comments(self):
        return Count(self.id)

class ArticleLikes(models.Model):
    likebool = models.BooleanField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_published = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.article.title +" : " + self.owner.get_short_name()

    def number_of_likes(self):
        return Count(self.id)

class UserFollowing(models.Model):
    followbool = models.BooleanField()
    following = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'following', unique=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'user')
    date_follow = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.owner.get_short_name() +" :follows: " + self.following.firstname

    def number_of_followers(self):
        return Count(self.id)

blog/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from .models import Article, ArticleComments
from django.conf import settings

class AddArticleForm(ModelForm):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'placeholder':'Title'}), max_length=200)
    article_image = forms.ImageField(required=False)
    description = forms.CharField(label="Content", widget=forms.Textarea(attrs={'placeholder':'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'}))

    class Meta:
        model = Article
        fields = ['title', 'article_image', 'description']

class UpdateArticleForm(ModelForm):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'placeholder':'Title'}), max_length=200)
    article_image = forms.ImageField(required=False)
    description = forms.CharField(label="Content", widget=forms.Textarea(attrs={'placeholder':'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'}))

    class Meta:
        model = Article
        fields = ['title', 'article_image', 'description']

class AddComment(ModelForm):
    content = forms.CharField(label="Comment", widget=forms.TextInput(attrs={'placeholder':'Enter a Comment'}))
    
    class Meta:
        model = ArticleComments
        fields = ['content']

class EditComment(ModelForm):
    content = forms.CharField(label="Comment", widget=forms.TextInput(attrs={'placeholder':'Enter a Comment'}))
    
    class Meta:
        model = ArticleComments
        fields = ['content']

blog/views.py
from django.shortcuts import (
    Http404,
    render, 
    HttpResponse, 
    redirect, 
    get_object_or_404, 
    HttpResponseRedirect)
from .forms import AddArticleForm, UpdateArticleForm, AddComment, EditComment
from .models import Article, FeaturedArticle, ArticleComments, ArticleLikes, UserFollowing
from django.core.paginator import Paginator
from django.db.models import Count
from users.models import User
from rest_framework import viewsets

#-----------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------

from rest_framework import generics
from .serializers import ArticleSerializer, CommentSerializer
from django.views.generic.base import TemplateView

def home_page(request):
    featured = Article.objects.filter(is_featured=True).order_by('?')[:3]
    article_list = Article.objects.all().order_by('-date_published')
    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    form = paginator.get_page(page)
    return render(request, 'blog/homepage.html', {'form': form, 'featured':featured})

def add_article(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            data = {'owner':request.user}
            form = AddArticleForm(request.POST, request.FILES, initial=data)
            if form.is_valid():
                addArticle = form.save(commit=False)
                addArticle.owner = request.user
                form.save()
                return redirect('blog:homepage')
        else:
            form = AddArticleForm()

        return render(request, 'blog/addarticle.html', {'form': form})
    else:
        return redirect('users:login')

def edit_article(request, article_id):
    if request.user.is_authenticated:
        qs = Article.objects.get(pk=article_id)
        data = {'article_image': qs.article_image,
                'title': qs.title,
                'description': qs.description}
        if request.user == qs.owner:
            if request.method == 'POST':
                form = UpdateArticleForm(request.POST, request.FILES, initial=data, instance=qs)
                if form.is_valid():
                        form.save()
                        return redirect('blog:userarticle', request.user.id)
                else:
                    form = UpdateArticleForm(initial=data)
            else:
                form = UpdateArticleForm(initial=data)

            return render(request, 'blog/editarticle.html', {'form': form})
        else:
            raise Http404("INVALID ACCESS")
    else:
        return redirect('users:login')

def delete_article(request, article_id):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_id, owner=request.user)
        article.delete()
        return redirect('blog:userarticle')
    else:
        return redirect('users:login')

def article_details(request, article_id):
    form = Article.objects.filter(pk=article_id)
    instance = get_object_or_404(Article, pk=article_id)
    commentForm = AddComment()
    loadComment = ArticleComments.objects.filter(article=instance).order_by('date_published')
    if request.user.is_authenticated:
        likes = ArticleLikes.objects.filter(article=instance, owner=request.user)
        totallikes = ArticleLikes.objects.filter(article=instance, likebool=True).count()
        return render(request, 'blog/articledetails.html', {'form': form, 
        'commentForm': commentForm, 'loadComment':loadComment, 'likes':likes,
        'totallikes':totallikes})
    else:
        return render(request, 'blog/articledetails.html', {'form': form, 
        'commentForm': commentForm, 'loadComment':loadComment})

def comment_add(request, article_id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            commentForm = AddComment(request.POST)
            if commentForm.is_valid():
                article = get_object_or_404(Article, pk=article_id)
                addComment = commentForm.save(commit=False)
                addComment.owner = request.user
                addComment.article = article
                commentForm.save()
            return redirect('blog:articledetails', article_id)
        else:
            return redirect('blog:articledetails', article_id)
    else:
        raise Http404("INVALID ACCESS")

def comment_edit(request, comment_id):
    if request.user.is_authenticated:
        comments = get_object_or_404(ArticleComments, pk=comment_id, owner=request.user)
        article = get_object_or_404(Article, pk=comments.article.id)
        data = {'content': comments.content}
        form = EditComment(initial=data)
        if request.method == 'POST':
            commentForm = EditComment(request.POST, instance=comments)
            if commentForm.is_valid():
                commentForm.save()
            return redirect('blog:articledetails', article.id)
        else:
            return render(request, 'blog/editcomment.html', {'form': form})
    else:
        raise Http404("INVALID ACCESS")

def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(ArticleComments, pk=comment_id, owner=request.user)
        article = get_object_or_404(Article, pk=comment.article.id)
        comment.delete()
        return redirect('blog:articledetails', article.id)
    else:
        raise Http404("INVALID ACCESS")

def article_like(request, article_id):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_id)
        likes = ArticleLikes.objects.filter(article=article, owner=request.user)
        if not likes:
            ArticleLikes.objects.create(likebool=True, article=article, owner=request.user)
        else:
            for like in likes:
                if like.likebool == True:
                    ArticleLikes.objects.filter(id = like.id).update(likebool = False)
                else:
                    ArticleLikes.objects.filter(id = like.id).update(likebool = True)

        return redirect('blog:articledetails', article.id)
    else:
        raise Http404("INVALID ACCESS")

def view_liked(request):
    if request.user.is_authenticated:
        form = ArticleLikes.objects.filter(owner=request.user, likebool=True).order_by('-date_published')
        return render(request, 'blog/likedarticlesview.html', {'form': form})
    else:
        raise Http404("INVALID ACCESS")

def user_articles(request, user_id):
    user = User.objects.get(pk=user_id)
    form = Article.objects.filter(owner=user_id).order_by('-date_published')
    if request.user.is_authenticated:
        follow = UserFollowing.objects.filter(following=user, owner=request.user)
        return render(request, 'blog/userarticles.html', {'form': form, 'user':user, 'follow':follow})
    else:
        return render(request, 'blog/userarticles.html', {'form': form, 'user':user})

def user_follow(request, user_id):
    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=user_id)
        follow = UserFollowing.objects.filter(following=user, owner=request.user)
        
        if not follow:
            UserFollowing.objects.create(followbool=True, following=user, owner=request.user)
        else:
            for fllw in follow:
                if fllw.followbool == True:
                    UserFollowing.objects.filter(id = fllw.id).delete()
                else:
                    UserFollowing.objects.filter(id = fllw.id).update(followbool = True)

        return redirect('blog:userarticle', user_id)
    else:
        raise Http404("INVALID ACCESS")


#
#--------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------NEW IMPLEMENTATION---------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------------------
#

class UserArticlesTemplateView(TemplateView):

    def get(self, request, **kwargs):
        user = User.objects.get(pk=kwargs.get('user_id'))
        return render(request, 'drf/userarticlesDRF.html', {'user': user})

class ArticleTemplateView(TemplateView):
    template_name = "drf/articleform.html"

class HomePageTemplateView(TemplateView):
    template_name = "drf/homepageDRF.html"

class ArticleDetailsTemplateView(TemplateView):

    def get(self, request, **kwargs):
        instance = get_object_or_404(Article, pk=kwargs.get('article_id'))
        return render(request, 'drf/articledetailsDRF.html', {'instance':instance})

class UserArticleLikesTemplateView(TemplateView):

    def get(self, request, **kwargs):
        return render(request, 'drf/userlikedarticlesDRF.html')

class EditUserTemplateView(TemplateView):
    
    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return render(request, "drf/edituserDRF.html")
        else:
            Http404("Invalid Access")

class RegisterUserTemplateView(TemplateView):
    
    def get(self, request, **kwargs):
        return render(request, "drf/registerDRF.html")

class ChangePassUserTemplateView(TemplateView):
    
    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return render(request, "drf/changepasswordDRF.html")
        else:
            Http404("Invalid Access")

templates/blog/articledetails.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Article Details{% endblock %}

{% block switch %}
    {% if user.is_authenticated %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:userarticle' request.user.id%}">Published Articles</a>
            <a class="dropdown-item" href="{% url 'blog:viewliked' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'users:edituser' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'users:editpass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
        <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary"> Login </a>
    {% endif %}
{% endblock%}

{% block content %}
    <div class="container">
        {% for details in form %}
            <div align="center">
                <h1 class="display-3">{{details.title}}</h1>
                <p>
                    <b>Author:</b> {{details.owner.get_full_name}} <b>date published:</b> {{details.date_published}}
                    {% if request.user == details.owner %}
                        <a href="{% url 'blog:editarticle' details.id%}"><i>edit</i></a>
                    {% endif %}
                </p>
                {% if details.article_image %}
                    <img class="img-responsive" src="{{ MEDIA_URL }}{{ details.article_image }}" width="600" height="320"></img>
                {% endif %}
            </div>
            <div class="articledetails">
                <p class="text-justify">{{details.description}}</p>
            </div>
        {% endfor %}
    </div>
    <div style="border-top:1px solid gray">
        <br>
        <div class="container">
            {% if user.is_authenticated %}
                <div>
                    <div class="row">
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-10">
                            {% for details in form %}
                                <div class="mb-2">
                                {% if likes %}
                                    {% for like in likes %}
                                        {% if like.likebool == True %}
                                            <a href="{% url 'blog:likearticle' details.id%}" class="btn btn-primary btn-sm">LIKED &nbsp<span class="badge badge-light">{{totallikes}}</span></a>
                                        {% else %}
                                            <a href="{% url 'blog:likearticle' details.id%}" class="btn btn-outline-primary btn-sm">LIKE &nbsp<span class="badge badge-light">{{totallikes}}</span></a>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <a href="{% url 'blog:likearticle' details.id%}" class="btn btn-outline-primary btn-sm">LIKE &nbsp<span class="badge badge-light">{{totallikes}}</span></a>
                                {% endif %}
                                </div>
                                <form method="POST" id="addArticle" name="addArticle" action="{% url 'blog:addcomment' details.id %}" novalidate>
                                {% csrf_token %}
                                    {% for hidden in commentForm.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% for field in commentForm.visible_fields %}
                                        <div class="form-group">
                                            <label>{{field.label}}</label>
                                            {{ field|add_class:'form-control' |add_error_class:'is-invalid' }}
                                            {% if field.errors %}
                                                <div class="invalid-feedback">
                                                    {{ field.errors }}
                                                </div>
                                            {% endif %}  
                                        </div>
                                    {% endfor %}
                                </form>
                            {% endfor %}
                            <div class="float-right">
                                <button type="submit" class="btn btn-outline-dark" form="addArticle">Add Comment</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    <br/>
    <br/>
    <div class="container">
        {% for comments in loadComment %}
        <div class="row">
            <div class="col-md-10">
                <div class="d-flex">
                    <img src="{{MEDIA_URL}}{{comments.owner.avatar}}" width="40" height="40">
                    <div>
                        {% if comments.owner.firstname %}
                            <p class="mb-0"> &nbsp<i><b>{{comments.owner.get_short_name}}:</b></i></p>
                        {% else %}
                            <p class="mb-0"> &nbsp<i><b>{{comments.owner.email}}:</b></i></p>
                        {% endif %}
                        <p> &nbsp{{comments.content}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                {% if request.user == comments.owner %}
                    <div class="text-right">
                        <a href="{% url 'blog:editcomment' comments.id %}" class="btn btn-outline-secondary btn-sm">Edit</a>
                        <a href="{% url 'blog:deletecomment' comments.id %}" class="btn btn-outline-danger btn-sm" >Delete</a>
                    </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
{% endblock %}

templates/blog/userarticles.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Articles{% endblock %}

{% block switch %}
    {% if request.user.is_authenticated %}
    <div class="input-group ">
        <input type="text" class="form-control" placeholder="search" aria-label="search" >
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-sm" type="button">search</button>
        </div>
    </div>
    &nbsp
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:userarticle' request.user.id%}">Published Articles</a>
            <a class="dropdown-item" href="{% url 'blog:viewliked' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'users:edituser' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'users:editpass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
        <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary"> Login </a>
    {% endif %}
{% endblock%}

{% block content %}
    <div class="container-fluid">
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                    <div align="center">
                        {% if request.user.id != user.id %}
                            {% if user.firstname %}
                            <h2> {{user.get_full_name}}'s Articles </h2>
                            {% else %}
                                {{user.email}}'s Articles
                            {% endif %}
                        {% else %}
                            <h2>Your Published Articles</h2>
                        {% endif %}
                    </div>
                        {% if form %}
                            <div align="center">
                                {% for article in form %}        
                                    <li>
                                        <a href="{% url 'blog:articledetails' article.id%}" ><b>{{article.title}}</b></a>
                                        {% if request.user.id == article.owner.id %}
                                            <a href="{% url 'blog:editarticle' article.id%}" class="btn btn-outline-secondary"> edit me </a>
                                            <button class="btn btn-outline-danger" type="button" data-toggle="modal" data-target="#deleteModal">delete me</button>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-3">
                    <div align="center">
                        {% if request.user.is_authenticated %}
                            {% if request.user.id != user.id %}
                                <div class="text-right">
                                {% if follow %}
                                    {% for fllw in follow %}
                                        {% if fllw.followbool == True %}
                                            <a href = "{% url 'blog:followuser' user.id%}" class="btn btn-primary btn-sm" ><b>Followed</b></a>
                                        {% else %}
                                            <a href = "{% url 'blog:followuser' user.id%}" class="btn btn-outline-primary btn-sm" ><b>Follow Me</b></a>
                                        {% endif %}      
                                    {% endfor %}      
                                {% else %}
                                    <a href = "{% url 'blog:followuser' user.id%}" class="btn btn-outline-primary btn-sm" ><b>Follow Me</b></a>
                                {% endif %}               
                                </div>
                            {% endif %}
                        {% endif %}
                        <img src="{{user.avatar.url}}" width="200px" height="200px">
                        <br/>
                        {% if user.firstname %}
                            {{user.get_full_name}}
                        {% else %}
                            {{user.email}}
                        {% endif %}
                        <br/>
                        <br/>
                        <div class="p-3 mb-3 bg-light rounded">
                            <h4 class="font-italic">About Me</h4>
                            <p class="mb-0">{{user.about_me}}</p>
                        </div>
                    </div>
                    </div>
                </div>
            </div>   
        </div>
    </div>
{% endblock %}

{% block modal %}
            <!--
            FOR MODAL
        -->
        {% for article in form %}
            <div class="modal fade" id="deleteModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirm Delete?</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure? <b>{{article.title}}</b> will be deleted</p>
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'blog:deletearticle' article.id%}" class="btn btn-outline-success">Yes</a>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock modal %}