blog/urls.py
from django.urls import path

from . import views
from .views import (
    ArticleTemplateView, 
    HomePageTemplateView, 
    UserArticlesTemplateView, 
    ArticleDetailsTemplateView,
    UserArticleLikesTemplateView,
    EditUserTemplateView,
    RegisterUserTemplateView,
    ChangePassUserTemplateView)
from .api import NewArticleViewSet, UserViewSet, CommentViewSet, LikeViewSet

app_name = 'blog'
urlpatterns = [
    path('', views.home_page, name = "homepage"),
    path('article/<int:user_id>', views.user_articles, name = "userarticle"),
    path('article/liked', views.view_liked, name = "viewliked"),
    path('article/add', views.add_article, name = "addarticle"),
    path('article/add/comment/<int:article_id>', views.comment_add, name = "addcomment"),
    path('article/edit/comment/<int:comment_id>', views.comment_edit, name = "editcomment"),
    path('article/delete/comment/<int:comment_id>', views.comment_delete, name = "deletecomment"),
    path('article/delete/<int:article_id>', views.delete_article, name = "deletearticle"),
    path('article/details/<int:article_id>', views.article_details, name = "articledetails"),
    path('article/edit/<int:article_id>', views.edit_article, name = "editarticle"),
    path('article/like/<int:article_id>', views.article_like, name = "likearticle"),

    path('accounts/follow/<int:user_id>', views.user_follow, name = "followuser"),

    path('drf/homepage', HomePageTemplateView.as_view(), name = "drfhome"),
    path('drf/user/register', RegisterUserTemplateView.as_view(), name = "drfuserregister"),
    path('drf/user/edit', EditUserTemplateView.as_view(), name = "drfuseredit"),
    path('drf/user/change/password', ChangePassUserTemplateView.as_view(), name = "drfchangepass"),
    path('drf/user/article/<int:user_id>', UserArticlesTemplateView.as_view(), name = "drfuserarticle"),
    path('drf/article/details/<int:article_id>', ArticleDetailsTemplateView.as_view(), name = "drfarticledetails"),
    path('drf/user/article/likes', UserArticleLikesTemplateView.as_view(), name = "drfuserlikearticle"),
]

socialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blog.urls')),
    path('api/', include('blog.endpoints')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('accounts/login', views.LoginView.as_view(), name = "login"),
    path('accounts/logout', views.LogoutView.as_view(), name = "logout"),
    path('accounts/register', views.RegisterUserView.as_view(), name = "register"),
    path('accounts/forget/password', views.reset_password, name = "resetpass"),
    path('accounts/edit/user', views.EditUserView.as_view(), name = "edituser"),
    path('accounts/edit/password', views.EditPassword.as_view(), name = "editpass"),
]

templates/drf/articledetailsDRF.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Article Details{% endblock %}


{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <form name="search_form">
        <div class="input-group ">
            <input type="text" class="form-control" placeholder="search" aria-label="search" name="search" name="search">
            <div class="input-group-append">
                <select class="form-control" name="search_type" id="search_type">
                    <option value="article">Article</option>
                    <option value="user">User</option>
                    <option value="tags">Tags</option>
                </select>
                <button class="btn btn-outline-secondary btn-sm" type="submit">search</button>
            </div>
        </div>
    </form>
    &nbsp
    {% if user.is_authenticated %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:drfuserarticle' request.user.id%}">Your Profile</a>
            <a class="dropdown-item" href="{% url 'blog:drfuserlikearticle' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'blog:drfuseredit' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'blog:drfchangepass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
        <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary"> Login </a>
    {% endif %}
{% endblock%}

{% block content %}
<input type="hidden" id="article_id" value="{{instance.id}}">
<input type="hidden" id="user_id" value="{{request.user.id}}">
    <div class="container" id="article_details">
    </div>
    <div style="border-top:1px solid gray">
        <br>
        <div class="container">
            {% if user.is_authenticated %}
                <div>
                    <div class="row">
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-10">
                                <div class="mb-2" id="like_button">
                                </div>
                                <form method="POST" id="addComment" name="addComment" action="{% url 'endpoint:drfcommentpost' instance.id%}" novalidate>
                                    {% csrf_token %}
                                        <div class="form-group">
                                            <label>Comment</label>
                                            <input type="text" id="content" name="content" class='form-control' placeholder='Enter a comment'>
                                            <div id="invalid_content" class="invalid-feedback">
                                            </div>
                                        </div>
                                </form>
                            <div class="text-right">
                                <button type="submit" class="btn btn-outline-dark" form="addComment">Add Comment</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="mb-2" id="like_button">
                </div>
            {% endif %}
        </div>
    </div>
    <br/>
    <div align="center">
        <h3>Comments</h3>
    </div>
    <br/>
    <div class="container" id="comment_section">
    </div>
{% endblock %}


{% block modal %}
<div class="modal fade" id="edit_comment" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Comment</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="editComment" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="content" class="col-form-label">Comment Content:</label>
                        <input type="text" class="form-control" id="comment_content" name="comment_content"></input>
                        <div id="invalid_comment_content" class="invalid-feedback">
                        </div>
                    </div>
                    <input type="hidden" class="form-control" id="edit_comment_id" name="edit_comment_id">
                    <input type="hidden" class="form-control" id="owner" name="user_id" value={{request.user.id}}>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary" form="editComment">Confirm</button>
                <button id="dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="delete_comment" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Comment</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="deleteComment" method="POST">
                {% csrf_token %}
                    <div align="center">
                        <label>Confirm Comment Delete?</label>
                    </div>
                    <input type="hidden" class="form-control" id="delete_comment_id" name="delete_comment_id">
                    <input type="hidden" class="form-control" id="owner" name="user_id" value={{request.user.id}}>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary" form="deleteComment">Confirm</button>
                <button id="dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="show_users" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">View Likers</h4>
            </div>
            <div class="modal-body" id="show_user_like">
            </div>
            <div class="modal-footer">
                <button id="dismiss_show_users" type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="edit_article" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Article</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="editArticle" class="article-form" enctype="multipart/form-data" method="POST">
                
                {% csrf_token %}
                    <div class="form-group">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title">
                        <div id="invalid_title" class="invalid-feedback">
                        </div>
                    </div>
                    <div id="display_default">
                    </div>
                    <div class="form-group">
                        <label for="article_image" class="col-form-label">Image:</label>
                        <input type="file" class="form-control" id="article_image">
                    </div>
                    <div class="form-group">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea rows="5" class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="tags" class="col-form-label">Tags:</label>
                        <input type="text" class="form-control" id="tags" name="tags">
                    </div>
                    <input type="hidden" class="form-control" id="owner" name="user_id" value={{request.user.id}}>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary" form="editArticle">Confirm</button>
                <button id="dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="search_output" role="dialog">
    <div id="search_div" class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Search Result</h4>
            </div>
            <div class="modal-body" id="search_base">
            </div>
            <div class="modal-footer">
                <button id="search_dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
{% endblock modal %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/articledetails.js' %}"></script>
{% endblock %}

templates/drf/changepasswordDRF.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Change Password{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <form name="search_form">
        <div class="input-group ">
            <input type="text" class="form-control" placeholder="search" aria-label="search" name="search" name="search">
            <div class="input-group-append">
                <select class="form-control" name="search_type" id="search_type">
                    <option value="article">Article</option>
                    <option value="user">User</option>
                    <option value="tags">Tags</option>
                </select>
                <button class="btn btn-outline-secondary btn-sm" type="submit">search</button>
            </div>
        </div>
    </form>
    &nbsp
    {% if user.is_authenticated %}
    <div class="btn-group">
        <button id="btn_name" name="btn_name" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:drfuserarticle' request.user.id%}">Your Profile</a>
            <a class="dropdown-item" href="{% url 'blog:drfuserlikearticle' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'blog:drfuseredit' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'blog:drfchangepass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
    <img id="profile_picture" src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% endif %}
{% endblock%}


{% block content %}
    <div class="container">
        <div>
            <form method="POST" id="updateUserForm" name="updateUserForm" novalidate>
            {% csrf_token %}
                <div class="form-group">
                    <label for="old_password" class="col-form-label">Old Password:</label>
                    <input type="password" class="form-control" id="old_password" name="old_password">
                    <div id="invalid_old_password" class="invalid-feedback">
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirm_new_password" class="col-form-label">New Password:</label>
                    <input type="password" class="form-control" id="confirm_new_password" name="confirm_new_password">
                    <div id="invalid_new_password" class="invalid-feedback">
                    </div>
                </div>
                <div class="form-group">
                    <label for="new_password" class="col-form-label">Confirm New Password:</label>
                    <input type="password" class="form-control" id="new_password" name="new_password">
                </div>
            </form>
            <div class="float-right">
                <button class="btn btn-outline-dark" type="button" data-toggle="modal" data-target="#editModal">Update</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
            <!--
            FOR MODAL
        -->
            <div class="modal fade" id="editModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirm Edit?</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-dark" form="updateUserForm">Yes</button>
                            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>

<div class="modal fade" id="search_output" role="dialog">
    <div id="search_div" class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Search Result</h4>
            </div>
            <div class="modal-body" id="search_base">
            </div>
            <div class="modal-footer">
                <button id="search_dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
{% endblock modal %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/changepassword.js' %}"></script>
{% endblock %}

templates/drf/homepageDRF.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Home{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <form name="search_form">
        <div class="input-group ">
            <input type="text" class="form-control" placeholder="search" aria-label="search" name="search" name="search">
            <div class="input-group-append">
                <select class="form-control" name="search_type" id="search_type">
                    <option value="article">Article</option>
                    <option value="user">User</option>
                    <option value="tags">Tags</option>
                </select>
                <button class="btn btn-outline-secondary btn-sm" type="submit">search</button>
            </div>
        </div>
    </form>
    &nbsp
    {% if user.is_authenticated %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:drfuserarticle' request.user.id%}">Your Profile</a>
            <a class="dropdown-item" href="{% url 'blog:drfuserlikearticle' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'blog:drfuseredit' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'blog:drfchangepass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
        <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary"> Login </a>
    {% endif %}
{% endblock%}


{% block content %}
<input id="user_id" name="user_id" type="hidden" value={{request.user.id}}></input>
    <div class="container-fluid">
        <div class="container">
        {% if user.is_authenticated %}

            <div class="text-right">
                <button id="add_article" name="add_article" class="btn btn-outline-primary btn-sm" type="button" data-toggle="modal" data-target="#addModal">ADD ARTICLE</button>
            </div>
        
        {% endif %}
            <br />
            <br />
                <div class="jumbotron" id="jumbotron">
                </div>
                <div class="row" id="featuredthumbnail">
                </div>
        </div>
        <br />
        <br />
        <div class = "container">
                <div>
                    <div align="center">
                        <h2><b>ARTICLES</b></h2>
                    </div>
                    <div class="row">
                        <div class="col-md-8" id="articles">
                        </div>
                        <div class="col-md-4">
                            <div class="p-3 mb-3 bg-light rounded">
                                <h4 class="font-italic">Starting a blog</h4>
                                <p class="mb-0">It seems like there are so many people out there who are either struggling for 
                                ideas for their existing blog, or want to start a blog but don’t know what topic to pick.</p>
                            </div>

                            <div class="p-3">
                                <h4 class="font-italic">Random Read</h4>
                                <ol id="random_read_list" class="list-unstyled mb-0">
                                </ol>
                            </div>

                            <div class="p-3">
                                <h4 class="font-italic">Elsewhere</h4>
                                <ol class="list-unstyled">
                                <li><a href="#">GitHub</a></li>
                                <li><a href="#">Twitter</a></li>
                                <li><a href="#">Facebook</a></li>
                                </ol>
                            </div>
                        </div>                
                    </div>
                </div>
                    <div align="center">
                    <form id="pagination_form">
                        <ul id="pagination_ul" class="pagination justify-content-center" >
                        </ul>
                    </form>
                    </div>
                </div>
        </div>
    </div>
{% endblock %}


{% block modal %}
<div class="modal fade" id="addModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Article</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div id="errors">
                </div>
                <form id="addArticle" class="article-form" method="POST" action="{% url 'endpoint:drflistarticle' %}" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title">
                        <div id="invalid_title" class="invalid-feedback">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="article_image" class="col-form-label">Image:</label>
                        <input type="file" class="form-control" id="article_image" name="article_image">
                    </div> 
                    <div class="form-group">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea rows="5" class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="tags" class="col-form-label">Tags:</label>
                        <input type="text" class="form-control" id="tags" name="tags">
                    </div>
                    <input type="hidden" class="form-control" id="owner" name="user_id" value={{request.user.id}}>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-outline-primary" form="addArticle">Confirm</button>
                <button id="dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="search_output" role="dialog">
    <div id="search_div" class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Search Result</h4>
            </div>
            <div class="modal-body" id="search_base">
            </div>
            <div class="modal-footer">
                <button id="search_dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="likes_output" role="dialog">
    <div id="likes_div" class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Likes</h4>
            </div>
            <div class="modal-body" id="likes_base">
            </div>
            <input type="hidden" id="article_id_cont"></input>
            <div class="modal-footer">
                <button id="likes_dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="comments_output" role="dialog">
    <div id="comments_div" class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Comments</h4>
            </div>
            <div class="modal-body" id="comments_base">
            </div>
            <input type="hidden" id="article_id_comment"></input>
            <div class="modal-footer">
                <button id="comments_dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
{% endblock modal %}


{% block javascript %}
    <script type="text/javascript" src="{% static 'js/homepage.js' %}"></script>
{% endblock %}

templates/drf/registerDRF.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Register{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <a href={% url 'users:login' %} class="btn btn-outline-secondary">Login</a>
    &nbsp
    <a href={% url 'users:resetpass' %} class="btn btn-outline-danger">Forgot Password</a>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            <form method="POST" id="registerForm" name="registerForm" novalidate>
            {% csrf_token %}
                <div class="form-group">
                    <label for="email" class="col-form-label">email:</label>
                    <input type="email" class="form-control" id="email" name="email">
                    <div id="invalid_email" class="invalid-feedback">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-form-label">Password:</label>
                    <input type="password" class="form-control" id="password" name="password">
                    <div id="invalid_password" class="invalid-feedback">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password2" class="col-form-label">Confirm Password:</label>
                    <input type="password" class="form-control" id="password2" name="password2">
                </div>
            </form>
            <div class="float-right">
                <button type="submit" class="btn btn-outline-dark" form="registerForm">Register</button>
            </div>
        </div>
    </div>
{% endblock %}



{% block javascript %}
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock %}