blog/urls.py
from django.urls import path

from . import views
from .views import (
    ArticleTemplateView, 
    HomePageTemplateView, 
    UserArticlesTemplateView, 
    ArticleDetailsTemplateView,
    UserArticleLikesTemplateView,
    EditUserTemplateView,
    RegisterUserTemplateView,
    ChangePassUserTemplateView)
from .api import NewArticleViewSet, UserViewSet, CommentViewSet, LikeViewSet

app_name = 'blog'
urlpatterns = [
    path('', views.home_page, name = "homepage"),
    path('article/<int:user_id>', views.user_articles, name = "userarticle"),
    path('article/liked', views.view_liked, name = "viewliked"),
    path('article/add', views.add_article, name = "addarticle"),
    path('article/add/comment/<int:article_id>', views.comment_add, name = "addcomment"),
    path('article/edit/comment/<int:comment_id>', views.comment_edit, name = "editcomment"),
    path('article/delete/comment/<int:comment_id>', views.comment_delete, name = "deletecomment"),
    path('article/delete/<int:article_id>', views.delete_article, name = "deletearticle"),
    path('article/details/<int:article_id>', views.article_details, name = "articledetails"),
    path('article/edit/<int:article_id>', views.edit_article, name = "editarticle"),
    path('article/like/<int:article_id>', views.article_like, name = "likearticle"),

    path('accounts/follow/<int:user_id>', views.user_follow, name = "followuser"),

    path('drf/homepage', HomePageTemplateView.as_view(), name = "drfhome"),
    path('drf/user/register', RegisterUserTemplateView.as_view(), name = "drfuserregister"),
    path('drf/user/edit', EditUserTemplateView.as_view(), name = "drfuseredit"),
    path('drf/user/change/password', ChangePassUserTemplateView.as_view(), name = "drfchangepass"),
    path('drf/user/article/<int:user_id>', UserArticlesTemplateView.as_view(), name = "drfuserarticle"),
    path('drf/article/details/<int:article_id>', ArticleDetailsTemplateView.as_view(), name = "drfarticledetails"),
    path('drf/user/article/likes', UserArticleLikesTemplateView.as_view(), name = "drfuserlikearticle"),
]

socialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blog.urls')),
    path('api/', include('blog.endpoints')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('accounts/login', views.LoginView.as_view(), name = "login"),
    path('accounts/logout', views.LogoutView.as_view(), name = "logout"),
    path('accounts/register', views.RegisterUserView.as_view(), name = "register"),
    path('accounts/forget/password', views.reset_password, name = "resetpass"),
    path('accounts/edit/user', views.EditUserView.as_view(), name = "edituser"),
    path('accounts/edit/password', views.EditPassword.as_view(), name = "editpass"),
]

templates/removed/articleform.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="article-form" action="{% url 'users:articleviewset' %}">
    {% csrf_token %}
        <input type="text" placeholder="title" name="title">
        <textarea placeholder="description" name="description"></textarea>
        <button type="submit">hello</button>
    </form>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
{% endblock content %}

templates/removed/guide.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Home{% endblock %}


{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    {% if user.is_authenticated %}
    <div class="input-group ">
        <input type="text" class="form-control" placeholder="search" aria-label="search" >
        <div class="input-group-append">
            <button class="btn btn-outline-secondary btn-sm" type="button">search</button>
        </div>
    </div>
    &nbsp
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:userarticle' request.user.id%}">Published Articles</a>
            <a class="dropdown-item" href="{% url 'blog:viewliked' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'users:edituser' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'users:editpass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
        <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-secondary"> Login </a>
    {% endif %}
{% endblock%}


{% block content %}
<h1>Hello world</h1>
    <ul id="mylist"></ul>
    {% comment %}
    <div class="container-fluid">
        <div class="container">
        {% if user.is_authenticated %}
            <!-- PAGINATION PART -->
            <!--########################################################################################################-->
        
            <div class="text-right">
                <button class="btn btn-outline-primary btn-sm" type="button" data-toggle="modal" data-target="#addModal">ADD ARTICLE</button>
            </div>
        
            <!--########################################################################################################-->
        
        {% endif %}
            <br />
            <br />
            {% for feature in featured %}
                {% if forloop.first %}
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-md-4">
                            <h2><b> {{ feature.title }} </b></h2>
                            <p>
                                <b>Author:</b> 
                                <a href="{% url 'blog:userarticle' feature.owner.id%}">
                                    {% if feature.owner.firstname %}
                                        {{feature.owner.get_full_name}} 
                                    {% else %}
                                        {{feature.owner.email}} 
                                    {% endif %}
                                </a>
                            </p>
                            <p>{{ feature.description|truncatechars:100 }}</p>
                            <a href="{% url 'blog:articledetails' feature.id%}" >
                                <b>Continue reading</b>
                            </a>
                                <div class="caption">
                                    <button class="btn btn-primary btn-sm">Likes &nbsp<span class="badge badge-light">{{article.articlelikes.number_of_likes}}</span></button>
                                    <button class="btn btn-secondary btn-sm">Comments &nbsp<span class="badge badge-light">{{article.articlelikes.number_of_comment}}</span></button>
                                </div>
                        </div>
                        <div class="col-md-8">
                            <img src="{{MEDIA_URL}}{{feature.article_image}}" style="width:100%; height:300px">  
                        </div>
                    </div>
                </div>
                <div class="row">
                {% else %}
                    <div class="col-md-6">
                        <div class="thumbnail" >
                            <div class="row">
                                <div class="col-md-6">
                                    <h2><b> {{ feature.title }} </b></h2>
                                    <p>
                                        <b>Author:</b> 
                                        <a href="{% url 'blog:userarticle' feature.owner.id%}">
                                            {% if feature.owner.firstname %}
                                                {{feature.owner.get_full_name}} 
                                            {% else %}
                                                {{feature.owner.email}} 
                                            {% endif %}
                                        </a>
                                    </p>
                                    {{ feature.description|truncatechars:100 }}
                                    <a href="{% url 'blog:articledetails' feature.id%}" >
                                        <b>Continue reading</b>
                                    </a>
                                </div>
                                <div class="col-md-6">
                                        <img src="{{MEDIA_URL}}{{feature.article_image}}" style="width:100%; height:200px">
                                </div>
                            </div>
                        <div class="caption">
                            <button class="btn btn-primary btn-sm">Likes &nbsp<span class="badge badge-light">{{article.articlelikes.number_of_likes}}</span></button>
                            <button class="btn btn-secondary btn-sm">Comments &nbsp<span class="badge badge-light">{{article.articlelikes.number_of_comment}}</span></button>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        <br />
        <br />
        <div class="container">
                <ul id="article-list"></ul>
        </div>
    </div>
    {% endcomment %}


{% endblock %}


{% block modal %}
            <div class="modal fade" id="addModal" role="dialog">
                <div class="modal-dialog modal-lg">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Add Article</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <form id="addArticle" class="article-form" method="POST" action="{% url 'blog:drfarticle' %}">
                            
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="title" class="col-form-label">Title:</label>
                                    <input type="text" class="form-control" id="title" name="title">
                                </div>
                                {% comment %} <div class="form-group">
                                    <label for="image" class="col-form-label">Image:</label>
                                    <input type="file" class="form-control" id="image">
                                </div> {% endcomment %}
                                <div class="form-group">
                                    <label for="description" class="col-form-label">Description:</label>
                                    <textarea class="form-control" id="description" name="description"></textarea>
                                </div>
                                <input type="hidden" class="form-control" id="user_id" name="user_id" value={{request.user.id}}>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-primary" form="addArticle">Confirm</button>
                            <button id="dismiss" type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
{% endblock modal %}




[{
    'id': 1,
    'title': 'foo',
},
{
    'id': 2,
    'title': 'bar',
}]


#List of articles
$.ajax({



}).done(function(data){
    var id = data.id
    get_comments(id);
    get_likes(id);

});


function get_comments(articleId) {
    $.get({'api_to_cmments}')
}


function get_likes(articleId) {
    $.get('/api/article/'+articleId+'/likes').done(function(data){
        
    });
}


// var myElem =$('#myId') # hashtag for ID
// var myElem =$('.myId') # class



// myELem.on('click', function(){

// })
$(document).ready(function(){
    console.log("I AM READY")
    /* get list of articles */
    // $.get('/api/article').done(function(data){
    //     data.forEach(function(e) {
    //         var temp = '<li class="article-'+e.id+'">'+ e.title + 
    //                     '<div class="comments">loading...</div>' +
    //                     '</li>';
    //         $('#mylist').append(temp);

    //         setTimeout(function(){
    //             loadComments();
    //         }, 1000);
            
    //         function loadComments() {
    //             var commentData = {'comment': 'hello world'};
    //             var commentTemplate = '<span class="small">'+ commentData.comment +'</span>'
    //             $('.article-'+e.id).find('.comments').html(commentTemplate);
    //         }


    //     });
    // });

    var articleForm = $('.article-form');


    $('.article-form').on('submit', function(event) {
        event.preventDefault();
        //create article
        var dt = $('#date').val(new Date($.now()));
        var url = $(this).attr('action');
        console.log($(this).serialize(), "data");
        var jqhr = $.ajax({
                url:url,
                method:$(this).attr('method'),
                data: $(this).serialize()
            }).done(function(data){
                var article = data;
                console.log(article, 'article data')
                // $.get('user/'+article.owner).done(function(data){
                //     var user = data;
                createTemplate(article)
                //});
                    

                
            }).errors(function(error) {
                console.log(error, 'error');
            });

            function createTemplate(article) {
                var template = 
                    "<div class=\"container\">"
                    +    "<div style=\"border-top:1px solid gray\">"
                    +        "<div><h2><b>" 
                    +            article.title
                    +            "</b></h2> <p><b> Author: </b>"
                    +            "<a>"
                    +                "author name or email"
                    +            "</a> <b>date published:</b>"
                    +        "</p></div>"
                    +    "<div class=\"articledetailshome\">"
                    +        "<p class=\"text-justify\">"
                    +            jQuery.trim(data.description).substring(0, 199).split(" ").slice(0, -1).join(" ") + "..."
                    +            "<a href=\"/article/details/"+article.id+"\" >"
                    +            "<b> Continue Reaing</b></a></p>"
                    +    "</div>"
                    +    "<button class=\"btn btn-primary btn-sm\" style=\"margin-right: 4px;\">Likes &nbsp<span class=\"badge badge-light\"></span></button>"
                    +    "<button class=\"btn btn-secondary btn-sm\">Comments &nbsp<span class=\"badge badge-light\"></span></button>"
                    +"</div><br/>";
                //$('.table').append(template);
                $('#articles').prepend(template);
                $('#addModal').modal('hide');
                console.log(data, 'data');
            }
    });
});

{/* <div class="articledetailshome">
<p class="text-justify">{{article.description|truncatechars:200}}
<a href="{% url 'blog:articledetails' article.id%}" >
<b> Continue reading</b></a></p>
</div> */}




# class ArticeViewSet(Viewset)

#     def detail(self, request, **kwargs):
#         article = Article.objects.get(kwargs.get('id'))
#         serializer = ArticleSerializer(article)
#         return Response(serializer.data, status=200)

#     def delete(self, request, **kwargs):
#         article = Article.objects.get(kwargs.get('id'))
#         article.delete()
#         return Response({}, status=202)
    
#     def add_comment(self, request, **kwargs):
#         article = get_object_or_404(Article, id=kwargs.get('id'))
#         data = request.data
#         serializer = CommentSerializer(data=data)
#         if serializer.is_valid():
#             data = serializer.save()
#             return Response(serializer.data, status=201)
#         return Response(serializer.errors, status=123)

#     def get_all_comments(self,)
#         comments = Comments.objects.filter(article__id=kwargs.get('id'))
#         serializer = CommentSerializer(comments, many=True)
#         return Response(serializer.data, status=200)

# url.py 
#     path('articles/<int:id>', ArticeViewSet.as_view({'get': 'detail'}), name="detail")
#     path('articles/<int:id>', ArticeViewSet.as_view({'post': 'delete'}), name="delete")
#     path('articles/<int:id>/comment', ArticeViewSet.as_view({'post': 'add_comment'}), name="add-comment")