blog/urls.py
from django.urls import path

from . import views
from .views import (
    ArticleTemplateView, 
    HomePageTemplateView, 
    UserArticlesTemplateView, 
    ArticleDetailsTemplateView,
    UserArticleLikesTemplateView,
    EditUserTemplateView,
    RegisterUserTemplateView,
    ChangePassUserTemplateView)
from .api import NewArticleViewSet, UserViewSet, CommentViewSet, LikeViewSet

app_name = 'blog'
urlpatterns = [
    path('', views.home_page, name = "homepage"),
    path('article/<int:user_id>', views.user_articles, name = "userarticle"),
    path('article/liked', views.view_liked, name = "viewliked"),
    path('article/add', views.add_article, name = "addarticle"),
    path('article/add/comment/<int:article_id>', views.comment_add, name = "addcomment"),
    path('article/edit/comment/<int:comment_id>', views.comment_edit, name = "editcomment"),
    path('article/delete/comment/<int:comment_id>', views.comment_delete, name = "deletecomment"),
    path('article/delete/<int:article_id>', views.delete_article, name = "deletearticle"),
    path('article/details/<int:article_id>', views.article_details, name = "articledetails"),
    path('article/edit/<int:article_id>', views.edit_article, name = "editarticle"),
    path('article/like/<int:article_id>', views.article_like, name = "likearticle"),

    path('accounts/follow/<int:user_id>', views.user_follow, name = "followuser"),

    path('drf/homepage', HomePageTemplateView.as_view(), name = "drfhome"),
    path('drf/user/register', RegisterUserTemplateView.as_view(), name = "drfuserregister"),
    path('drf/user/edit', EditUserTemplateView.as_view(), name = "drfuseredit"),
    path('drf/user/change/password', ChangePassUserTemplateView.as_view(), name = "drfchangepass"),
    path('drf/user/article/<int:user_id>', UserArticlesTemplateView.as_view(), name = "drfuserarticle"),
    path('drf/article/details/<int:article_id>', ArticleDetailsTemplateView.as_view(), name = "drfarticledetails"),
    path('drf/user/article/likes', UserArticleLikesTemplateView.as_view(), name = "drfuserlikearticle"),
]

socialblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blog.urls')),
    path('api/', include('blog.endpoints')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('accounts/login', views.LoginView.as_view(), name = "login"),
    path('accounts/logout', views.LogoutView.as_view(), name = "logout"),
    path('accounts/register', views.RegisterUserView.as_view(), name = "register"),
    path('accounts/forget/password', views.reset_password, name = "resetpass"),
    path('accounts/edit/user', views.EditUserView.as_view(), name = "edituser"),
    path('accounts/edit/password', views.EditPassword.as_view(), name = "editpass"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from PIL import Image



class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None,):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('Users must enter a password')    

        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(('email address'), unique=True)
    firstname = models.CharField(('first name'), max_length=30, blank=True)
    lastname = models.CharField(('last name'), max_length=30, blank=True)
    about_me = models.TextField(('about me'), blank=True)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
    is_active = models.BooleanField(('active'), default=True)
    is_staff = models.BooleanField(('staff'), default=False)
    is_superuser = models.BooleanField(('superuser'), default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default.png')
    
    #avatar = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.firstname, self.lastname)
        return full_name.strip()

    def get_short_name(self):
        # The user is identified by their email address
        return self.firstname

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

users/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import authenticate, login, logout
from .models import User

"""
    class UserRegForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def uniqueEmail(self, request):
        email = self.cleaned_data.get('email')
        usrs = User.objects.get()
        if email in usrs.email:
            return True
        else:
            return False
"""

class UserLoginForm(forms.Form):
    email = forms.CharField(label="Email", widget=forms.EmailInput(attrs={'placeholder': 'email@domain.com'}), required=True)
    password = forms.CharField(label= "Password", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), required=True)

    def auth(self, request):
        uname = self.cleaned_data.get('email')
        pword = self.cleaned_data.get('password')
        return authenticate(request, username=uname, password=pword)

class UpdateUserForm(ModelForm):
    avatar = forms.ImageField()
    email = forms.CharField(label="Email", widget=forms.EmailInput(attrs={'placeholder': 'email@domain.com'}), required=True)
    firstname = forms.CharField(label="First Name", widget=forms.TextInput(attrs={'placeholder':'First Name'}), max_length=200, required=False)
    lastname = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={'placeholder':'Last Name'}), max_length=200, required=False)
    about_me = forms.CharField(label="About Me", widget=forms.Textarea(attrs={'placeholder':'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris'}), required=False)

    class Meta:
        model = User
        fields = ['avatar', 'email', 'firstname', 'lastname', 'about_me']

class UserRegForm(ModelForm):
    email = forms.CharField(label="Email", widget=forms.EmailInput(attrs={'placeholder': 'email@domain.com'}), required=True)
    password = forms.CharField(label= "Password", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), required=True)
    password2 = forms.CharField(label= "Confirm Password", widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}), required=True)

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean_email(self):
       email = self.cleaned_data.get('email')
       qs = User.objects.filter(email=email)
       if qs.exists():
           raise forms.ValidationError("email is taken")
       return email

    def clean_password2(self):
       # Check that the two password entries match
       password1 = self.cleaned_data.get("password")
       password2 = self.cleaned_data.get("password2")

       if password1 and password2 and password1 != password2:
           raise forms.ValidationError("Passwords don't match")

       return password2

    def save(self, commit=True):
        instance = super(UserRegForm, self).save(commit=False)
        instance.set_password(self.cleaned_data.get('password'))

        if commit:
            instance.save()

        return instance

users/views.py
from django.shortcuts import (
    render, 
    HttpResponse, 
    redirect, 
    get_object_or_404, 
    HttpResponseRedirect)
from django.contrib.auth import (
    authenticate, 
    login, 
    logout)
from .models import User 
from .forms import (
    UserLoginForm, 
    UserRegForm, 
    UpdateUserForm)
from django.contrib.auth.forms import (
    PasswordChangeForm, 
    PasswordResetForm)
from django.views.generic.base import TemplateView


from rest_framework import generics

# Create your views here.

class LogoutView(TemplateView):
    
    def get(self, request):
        logout(request)
        return redirect('users:login')

class LoginView(TemplateView):

    def get(self, request):
        form = UserLoginForm()
        return render(request, 'users/login.html', {'form':form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = form.auth(request)
            if user is not None:
                login(request, user)
                return redirect('blog:drfhome')
            else:
                form = UserLoginForm(request.POST)
                form.add_error('password', "Invalid Password")
                return render(request, 'users/login.html', {'form':form})
        else:
            return render(request, 'users/login.html', {'form':form})

class RegisterUserView(TemplateView):

    def get(self, request):
        form = UserRegForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request):
        form = UserRegForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(email=user.email, password=form.cleaned_data.get('password'))
            if user is not None:
                login(request, user)
                return redirect('blog:drfuseredit')
        else:
            form = UserRegForm(request.POST)
        return render(request, 'users/register.html', {'form': form})

class EditUserView(TemplateView):

    def get(self, request):
        if request.user.is_authenticated:
            data = {'userid': request.user.id,
            'avatar': request.user.avatar,
            'email': request.user.email,
            'firstname': request.user.firstname,
            'lastname': request.user.lastname,
            'about_me': request.user.about_me}
            
            form = UpdateUserForm(initial=data)
            return render(request, 'users/edituser.html', {'form': form})
        else:
            return redirect('users:login')

    def post(self, request):
        if request.user.is_authenticated:
            form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('blog:homepage')
            else:
                form = UpdateUserForm(request.POST)
        else:
            return redirect('users:login')


class EditPassword(TemplateView):

    def get(self, request):
        if request.user.is_authenticated:
            form = PasswordChangeForm(request.user)
            return render(request, 'users/editpassword.html', {'form': form})
        else:
            return redirect('users:login')

    def post(self, request):
        if request.user.is_authenticated:
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                form.save()
            return redirect('users:logout')
        else:
            return redirect('users:login')


def reset_password(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            pass
            #form.save() 
            return redirect('users:login')
        else:
            form = PasswordResetForm(request.POST)
    else:
        form = PasswordResetForm()  
    return render(request, 'users/resetpassword.html', {'form': form})

templates/users/editpassword.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Edit Password{% endblock %}


{% block switch %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:userarticle' request.user.id%}">Published Articles</a>
            <a class="dropdown-item" href="{% url 'blog:viewliked' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'users:edituser' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'users:editpass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
    <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <form method="POST" id="updateUserForm" name="updateUserForm" novalidate>
            {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
                        {% if field.errors %}
                            <div class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}  
                    </div>
                {% endfor %}
            </form>
            <div class="float-right">
                <button class="btn btn-outline-dark" type="button" data-toggle="modal" data-target="#editModal">Update</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
            <!--
            FOR MODAL
        -->
            <div class="modal fade" id="editModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirm Edit?</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-dark" form="updateUserForm">Yes</button>
                            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
{% endblock modal %}

templates/users/edituser.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Edit User Profile{% endblock %}


{% block switch %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.firstname %}
                {{ request.user.firstname }}
            {% else %}
                {{ request.user.email }}
            {% endif %}
        </button>
        <div class="dropdown-menu ">
            <a class="dropdown-item" href="{% url 'blog:userarticle' request.user.id%}">Published Articles</a>
            <a class="dropdown-item" href="{% url 'blog:viewliked' %}" >Liked Articles</a>
            <a class="dropdown-item" href="{% url 'users:edituser' %}">Edit User Details</a>
            <a class="dropdown-item" href="{% url 'users:editpass' %}">Edit Password</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}" >Logout</a>
        </div>
    </div>
    &nbsp
    <img src="{{ request.user.avatar.url }}" width="40" height="40"></img>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <form method="POST" id="updateUserForm" name="updateUserForm" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{ field|add_class:'form-control' |add_error_class:'is-invalid' }}
                        {% if field.errors %}
                            <div class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}  
                    </div>
                {% endfor %}
            </form>
            <div class="float-right">
                <button class="btn btn-outline-dark" type="button" data-toggle="modal" data-target="#editModal">Update</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block modal %}
            <!--
            FOR MODAL
        -->
            <div class="modal fade" id="editModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirm Edit?</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-dark" form="updateUserForm">Yes</button>
                            <button type="button" class="btn btn-outline-danger" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
{% endblock modal %}

templates/users/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Login{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <a href={% url 'blog:drfuserregister' %} class="btn btn-outline-secondary">Register</a>
    &nbsp
    <a href={% url 'users:resetpass' %} class="btn btn-outline-danger">Forgot Password</a>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <form method="POST" action="{% url 'users:login' %}" id="loginForm" name="loginForm" novalidate>
            {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
                        {% if field.errors %}
                            <div class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}  
                    </div>
                {% endfor %}
            </form>
            <div class="float-right">
                <button type="submit" class="btn btn-outline-dark" form="loginForm">Login</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Register{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <a href={% url 'users:login' %} class="btn btn-outline-secondary">Login</a>
    &nbsp
    <a href={% url 'users:resetpass' %} class="btn btn-outline-danger">Forgot Password</a>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <form method="POST" action="{% url 'users:register' %}" id="registerForm" name="registerForm" novalidate>
            {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
                        {% if field.errors %}
                            <div class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}  
                    </div>
                {% endfor %}
            </form>
            <div class="float-right">
                <button type="submit" class="btn btn-outline-dark" form="registerForm">Register</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/resetpassword.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Reset Password{% endblock %}

{% block home %}
    <a href="{% url 'blog:drfhome' %}" class="btn btn-outline-secondary">Home</a>
{% endblock %}

{% block switch %}
    <a href={% url 'users:login' %} class="btn btn-outline-secondary">Login</a>
    &nbsp
    <a href={% url 'blog:drfuserregister' %} class="btn btn-outline-secondary">Register</a>
{% endblock%}

{% block content %}
    <div class="container">
        <div>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <form method="POST" action="{% url 'users:resetpass' %}" id="resetPassForm" name="resetPassForm" novalidate>
            {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label>{{field.label}}</label>
                        {{ field|add_class:'form-control'|add_error_class:'is-invalid' }}
                        {% if field.errors %}
                            <div class="invalid-feedback">
                                {{ field.errors }}
                            </div>
                        {% endif %}  
                    </div>
                {% endfor %}
            </form>
            <div class="float-right">
                <button type="submit" class="btn btn-outline-dark" form="resetPassForm">Reset Password</button>
            </div>
        </div>
    </div>
{% endblock %}